[tool.poetry]
name = "ontollm"
version = "0.3.1"
description = "OntoLLM"
authors = ["Chris Mungall <cjmungall@lbl.gov>"]
license = "BSD-3"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7,<4.0"
click = ">=8.1.3"
# TODO Remove dependence on openai
openai = ">=0.27.8"
oaklib = ">=0.5.15"
gilda = ">=1.0.0"
jsonlines = ">=3.1.0"
python-multipart = "^0.0.5"
beautifulsoup4 = ">=4.11.1"
eutils = ">=0.6.0"
class-resolver = ">=0.4.2"
inflect = ">=6.0.2"
bioc = ">=2.0.post5"
wikipedia = ">=1.4.0"
# TODO Remove dependence on tiktoken
tiktoken = ">=0.3.3"
airium = ">=0.2.5"
httpx = ">=0.23.3"
aiohttp = ">=3.8.4"
inflection = ">=0.5.1"
nlpcloud = ">=1.0.39"
fastapi = {version = ">=0.88.0", optional = true}
uvicorn = {version = ">=0.20.0", optional = true}
Jinja2 = {version = ">=3.1.2", optional = true}
sphinx = {version = ">=5.3.0", extras = ["docs"], optional = true}
sphinx-rtd-theme = {version = ">=1.0.0", extras = ["docs"], optional = true}
sphinx-autodoc-typehints = {version = ">=1.19.4", extras = ["docs"], optional = true}
sphinx-click = {version = ">=4.3.0", extras = ["docs"], optional = true}
myst-parser = {version = ">=0.18.1", extras = ["docs"], optional = true}
recipe-scrapers = {version = ">=14.35.0", extras = ["recipes"], optional = true}
textract = {version = "*", extras = ["textract"], optional = true}
cachier = ">=2.1.0"
# TODO See if it can also work with a downloaded version
wikipedia-api = ">=0.5.8"
pystow = "^0.5.0"
requests-cache = ">=1.0.1"
streamlit = ">=1.22.0"
#TODO Remove dependency on gpt4
gpt4 = ">=0.0.1"
"ruamel.yaml" = ">=0.17.31"
requests = "^2.31.0"
huggingface_hub  = {version = ">=0.15.1", extras = ["huggingface"], optional = true}
llm = "^0.8"
llm-gpt4all = "^0.1.1"
linkml = "^1.5.7"
linkml-owl = "^0.3.0"

[tool.poetry.dev-dependencies]
pytest = ">=7.1.2"
setuptools = ">=65.5.0"
tox = ">=3.25.1"
mkdocs-mermaid2-plugin = ">=0.6.0"

[tool.poetry.scripts]
ontollm = "ontollm.cli:main"
web-ontollm = "ontollm.webapp.main:start"

[tool.poetry.extras]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx-autodoc-typehints",
    "sphinx-click",
    "myst-parser"
    ]
web = [
    "fastapi",
    "uvicorn",
    "Jinja2"
]
recipes = [
    "recipe-scrapers"
]
gpt4all = [
    "gpt4all"
]
textract = [
    "textract"
]
huggingface = [
    "huggingface_hub"
]

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
papermill = "^2.4.0"

[tool.poetry-dynamic-versioning]
enable = false
vcs = "git"
style = "pep440"

[tool.black]
line-length = 100
target-version = ["py38", "py39", "py310"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
include_trailing_comma = true
reverse_relative = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
