{
   "ENVO": "http://example.org/UNKNOWN/ENVO/",
   "ENVTHES": "http://example.org/UNKNOWN/ENVTHES/",
   "GAZ": "http://example.org/UNKNOWN/GAZ/",
   "RO": "http://purl.obolibrary.org/obo/RO_",
   "biolink": "http://example.org/UNKNOWN/biolink/",
   "core": "http://w3id.org/ontogpt/core/",
   "envmd": "http://w3id.org/ontogpt/environmental-metadata",
   "linkml": "https://w3id.org/linkml/",
   "rdfs": "http://example.org/UNKNOWN/rdfs/",
   "AnnotatorResult": {
      "@id": "core:AnnotatorResult"
   },
   "Any": {
      "@id": "linkml:Any"
   },
   "CompoundExpression": {
      "@id": "core:CompoundExpression"
   },
   "ExtractionResult": {
      "@id": "core:ExtractionResult"
   },
   "NamedEntity": {
      "@id": "core:NamedEntity"
   },
   "Publication": {
      "@id": "core:Publication"
   },
   "RelationshipType": {
      "@id": "core:RelationshipType"
   },
   "TextWithTriples": {
      "@id": "core:TextWithTriples"
   },
   "Triple": {
      "@id": "core:Triple"
   }
}
